<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->insert([
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Barat'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Barat Daya'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Besar'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Jaya'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Selatan'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Singkil'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tamiang'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tengah'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tenggara'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Timur'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Utara'],
            ['province_id' => 1, 'name' => 'Kabupaten Bener Meriah'],
            ['province_id' => 1, 'name' => 'Kabupaten Bireuen'],
            ['province_id' => 1, 'name' => 'Kabupaten Gayo Lues'],
            ['province_id' => 1, 'name' => 'Kabupaten Nagan Raya'],
            ['province_id' => 1, 'name' => 'Kabupaten Pidie'],
            ['province_id' => 1, 'name' => 'Kabupaten Pidie Jaya'],
            ['province_id' => 1, 'name' => 'Kabupaten Simeulue'],
            ['province_id' => 1, 'name' => 'Kota Banda Aceh'],
            ['province_id' => 1, 'name' => 'Kota Lhokseumawe'],
            ['province_id' => 1, 'name' => 'Kota Sabang'],
            ['province_id' => 1, 'name' => 'Kota Subulussalam'],
            ['province_id' => 2, 'name' => 'Kabupaten Asahan'],
            ['province_id' => 2, 'name' => 'Kabupaten Batu Bara'],
            ['province_id' => 2, 'name' => 'Kabupaten Dairi'],
            ['province_id' => 2, 'name' => 'Kabupaten Deli Serdang'],
            ['province_id' => 2, 'name' => 'Kabupaten Humbang Hasundutan'],
            ['province_id' => 2, 'name' => 'Kabupaten Karo'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu Selatan'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu Utara'],
            ['province_id' => 2, 'name' => 'Kabupaten Langkat'],
            ['province_id' => 2, 'name' => 'Kabupaten Mandailing Natal'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Barat'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Selatan'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Utara'],
            ['province_id' => 2, 'name' => 'Kabupaten Padang Lawas'],
            ['province_id' => 2, 'name' => 'Kabupaten Padang Lawas Utara'],
            ['province_id' => 2, 'name' => 'Kabupaten Pakpak Bharat'],
            ['province_id' => 2, 'name' => 'Kabupaten Samosir'],
            ['province_id' => 2, 'name' => 'Kabupaten Serdang Bedagai'],
            ['province_id' => 2, 'name' => 'Kabupaten Simalungun'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Selatan'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Tengah'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Utara'],
            ['province_id' => 2, 'name' => 'Kabupaten Toba'],
            ['province_id' => 2, 'name' => 'Kota Binjai'],
            ['province_id' => 2, 'name' => 'Kota Gunungsitoli'],
            ['province_id' => 2, 'name' => 'Kota Medan'],
            ['province_id' => 2, 'name' => 'Kota Padangsidimpuan'],
            ['province_id' => 2, 'name' => 'Kota Pematangsiantar'],
            ['province_id' => 2, 'name' => 'Kota Sibolga'],
            ['province_id' => 2, 'name' => 'Kota Tanjungbalai'],
            ['province_id' => 2, 'name' => 'Kota Tebing Tinggi'],
            ['province_id' => 3, 'name' => 'Kabupaten Banyuasin'],
            ['province_id' => 3, 'name' => 'Kabupaten Empat Lawang'],
            ['province_id' => 3, 'name' => 'Kabupaten Lahat'],
            ['province_id' => 3, 'name' => 'Kabupaten Muara Enim'],
            ['province_id' => 3, 'name' => 'Kabupaten Musi Banyuasin'],
            ['province_id' => 3, 'name' => 'Kabupaten Musi Rawas'],
            ['province_id' => 3, 'name' => 'Kabupaten Musi Rawas Utara'],
            ['province_id' => 3, 'name' => 'Kabupaten Ogan Ilir'],
            ['province_id' => 3, 'name' => 'Kabupaten Ogan Komering Ilir'],
            ['province_id' => 3, 'name' => 'Kabupaten Ogan Komering Ulu'],
            ['province_id' => 3, 'name' => 'Kabupaten Ogan Komering Ulu Selatan'],
            ['province_id' => 3, 'name' => 'Kabupaten Ogan Komering Ulu Timur'],
            ['province_id' => 3, 'name' => 'Kabupaten Penukal Abab Lematang Ilir'],
            ['province_id' => 3, 'name' => 'Kota Lubuk Linggau'],
            ['province_id' => 3, 'name' => 'Kota Pagaralam'],
            ['province_id' => 3, 'name' => 'Kota Palembang'],
            ['province_id' => 3, 'name' => 'Kota Prabumulih'],
            ['province_id' => 4, 'name' => 'Kabupaten Agam'],
            ['province_id' => 4, 'name' => 'Kabupaten Dharmasraya'],
            ['province_id' => 4, 'name' => 'Kabupaten Kepulauan Mentawai'],
            ['province_id' => 4, 'name' => 'Kabupaten Lima Puluh Kota'],
            ['province_id' => 4, 'name' => 'Kabupaten Padang Pariaman'],
            ['province_id' => 4, 'name' => 'Kabupaten Pasaman'],
            ['province_id' => 4, 'name' => 'Kabupaten Pasaman Barat'],
            ['province_id' => 4, 'name' => 'Kabupaten Pesisir Selatan'],
            ['province_id' => 4, 'name' => 'Kabupaten Sijunjung'],
            ['province_id' => 4, 'name' => 'Kabupaten Solok'],
            ['province_id' => 4, 'name' => 'Kabupaten Solok Selatan'],
            ['province_id' => 4, 'name' => 'Kabupaten Tanah Datar'],
            ['province_id' => 4, 'name' => 'Kota Bukittinggi'],
            ['province_id' => 4, 'name' => 'Kota Padang'],
            ['province_id' => 4, 'name' => 'Kota Padang Panjang'],
            ['province_id' => 4, 'name' => 'Kota Pariaman'],
            ['province_id' => 4, 'name' => 'Kota Payakumbuh'],
            ['province_id' => 4, 'name' => 'Kota Sawahlunto'],
            ['province_id' => 4, 'name' => 'Kota Solok'],
            ['province_id' => 5, 'name' => 'Kabupaten Bengkulu Selatan'],
            ['province_id' => 5, 'name' => 'Kabupaten Bengkulu Tengah'],
            ['province_id' => 5, 'name' => 'Kabupaten Bengkulu Utara'],
            ['province_id' => 5, 'name' => 'Kabupaten Kaur'],
            ['province_id' => 5, 'name' => 'Kabupaten Kepahiang'],
            ['province_id' => 5, 'name' => 'Kabupaten Lebong'],
            ['province_id' => 5, 'name' => 'Kabupaten Mukomuko'],
            ['province_id' => 5, 'name' => 'Kabupaten Rejang Lebong'],
            ['province_id' => 5, 'name' => 'Kabupaten Seluma'],
            ['province_id' => 5, 'name' => 'Kota Bengkulu'],
            ['province_id' => 6, 'name' => 'Kabupaten Bengkalis'],
            ['province_id' => 6, 'name' => 'Kabupaten Indragiri Hilir'],
            ['province_id' => 6, 'name' => 'Kabupaten Indragiri Hulu'],
            ['province_id' => 6, 'name' => 'Kabupaten Kampar'],
            ['province_id' => 6, 'name' => 'Kabupaten Kepulauan Meranti'],
            ['province_id' => 6, 'name' => 'Kabupaten Kuantan Singingi'],
            ['province_id' => 6, 'name' => 'Kabupaten Pelalawan'],
            ['province_id' => 6, 'name' => 'Kabupaten Rokan Hulu'],
            ['province_id' => 6, 'name' => 'Kabupaten Siak'],
            ['province_id' => 6, 'name' => 'Kota Dumai'],
            ['province_id' => 6, 'name' => 'Kota Pekanbaru'],
            ['province_id' => 7, 'name' => 'Kabupaten Bintan'],
            ['province_id' => 7, 'name' => 'Kabupaten Karimun'],
            ['province_id' => 7, 'name' => 'Kabupaten Kepulauan Anambas'],
            ['province_id' => 7, 'name' => 'Kabupaten Lingga'],
            ['province_id' => 7, 'name' => 'Kabupaten Natuna'],
            ['province_id' => 7, 'name' => 'Kota Batam'],
            ['province_id' => 7, 'name' => 'Kota Tanjungpinang'],
            ['province_id' => 8, 'name' => 'Kabupaten Batanghari'],
            ['province_id' => 8, 'name' => 'Kabupaten Bungo'],
            ['province_id' => 8, 'name' => 'Kabupaten Kerinci'],
            ['province_id' => 8, 'name' => 'Kabupaten Merangin'],
            ['province_id' => 8, 'name' => 'Kabupaten Muaro Jambi'],
            ['province_id' => 8, 'name' => 'Kabupaten Sarolangun'],
            ['province_id' => 8, 'name' => 'Kabupaten Tanjung Jabung Barat'],
            ['province_id' => 8, 'name' => 'Kabupaten Tanjung Jabung Timur'],
            ['province_id' => 8, 'name' => 'Kabupaten Tebo'],
            ['province_id' => 8, 'name' => 'Kota Jambi'],
            ['province_id' => 8, 'name' => 'Kota Sungai Penuh'],
            ['province_id' => 9, 'name' => 'Kabupaten Lampung Barat'],
            ['province_id' => 9, 'name' => 'Kabupaten Lampung Selatan'],
            ['province_id' => 9, 'name' => 'Kabupaten Lampung Tengah'],
            ['province_id' => 9, 'name' => 'Kabupaten Lampung Timur'],
            ['province_id' => 9, 'name' => 'Kabupaten Lampung Utara'],
            ['province_id' => 9, 'name' => 'Kabupaten Mesuji'],
            ['province_id' => 9, 'name' => 'Kabupaten Pesawaran'],
            ['province_id' => 9, 'name' => 'Kabupaten Pesisir Barat'],
            ['province_id' => 9, 'name' => 'Kabupaten Pringsewu'],
            ['province_id' => 9, 'name' => 'Kabupaten Tanggamus'],
            ['province_id' => 9, 'name' => 'Kabupaten Tulang Bawang'],
            ['province_id' => 9, 'name' => 'Kabupaten Tulang Bawang Barat'],
            ['province_id' => 9, 'name' => 'Kabupaten Way Kanan'],
            ['province_id' => 9, 'name' => 'Kota Bandar Lampung'],
            ['province_id' => 9, 'name' => 'Kota Metro'],
            ['province_id' => 10, 'name' => 'Kabupaten Bangka'],
            ['province_id' => 10, 'name' => 'Kabupaten Bangka Barat'],
            ['province_id' => 10, 'name' => 'Kabupaten Bangka Selatan'],
            ['province_id' => 10, 'name' => 'Kabupaten Bangka Tengah'],
            ['province_id' => 10, 'name' => 'Kabupaten Belitung'],
            ['province_id' => 10, 'name' => 'Kabupaten Belitung Timur'],
            ['province_id' => 10, 'name' => 'Kota Pangkalpinang'],
            ['province_id' => 11, 'name' => 'Kabupaten Bengkayang'],
            ['province_id' => 11, 'name' => 'Kabupaten Kapuas Hulu'],
            ['province_id' => 11, 'name' => 'Kabupaten Kayong Utara'],
            ['province_id' => 11, 'name' => 'Kabupaten Ketapang'],
            ['province_id' => 11, 'name' => 'Kabupaten Kubu Raya'],
            ['province_id' => 11, 'name' => 'Kabupaten Landak'],
            ['province_id' => 11, 'name' => 'Kabupaten Melawi'],
            ['province_id' => 11, 'name' => 'Kabupaten Mempawah'],
            ['province_id' => 11, 'name' => 'Kabupaten Sambas'],
            ['province_id' => 11, 'name' => 'Kabupaten Sekadau'],
            ['province_id' => 11, 'name' => 'Kabupaten Sintang'],
            ['province_id' => 11, 'name' => 'Kota Pontianak'],
            ['province_id' => 11, 'name' => 'Kota Singkawang'],
            ['province_id' => 12, 'name' => 'Kabupaten Berau'],
            ['province_id' => 12, 'name' => 'Kabupaten Kutai Barat'],
            ['province_id' => 12, 'name' => 'Kabupaten Kutai Kartanegara'],
            ['province_id' => 12, 'name' => 'Kabupaten Kutai Timur'],
            ['province_id' => 12, 'name' => 'Kabupaten Mahakam Ulu'],
            ['province_id' => 12, 'name' => 'Kabupaten Paser'],
            ['province_id' => 12, 'name' => 'Kabupaten Penajam Paser Utara'],
            ['province_id' => 12, 'name' => 'Kota Balikpapan'],
            ['province_id' => 12, 'name' => 'Kota Bontang'],
            ['province_id' => 12, 'name' => 'Kota Samarinda'],
            ['province_id' => 13, 'name' => 'Kabupaten Balangan'],
            ['province_id' => 13, 'name' => 'Kabupaten Banjar'],
            ['province_id' => 13, 'name' => 'Kabupaten Barito Kuala'],
            ['province_id' => 13, 'name' => 'Kabupaten Hulu Sungai Selatan'],
            ['province_id' => 13, 'name' => 'Kabupaten Hulu Sungai Tengah'],
            ['province_id' => 13, 'name' => 'Kabupaten Kotabaru'],
            ['province_id' => 13, 'name' => 'Kabupaten Tabalong'],
            ['province_id' => 13, 'name' => 'Kabupaten Tanah Bumbu'],
            ['province_id' => 13, 'name' => 'Kabupaten Tanah Laut'],
            ['province_id' => 13, 'name' => 'Kota Banjarbaru'],
            ['province_id' => 13, 'name' => 'Kota Banjarmasin'],
            ['province_id' => 14, 'name' => 'Kabupaten Barito Selatan'],
            ['province_id' => 14, 'name' => 'Kabupaten Barito Timur'],
            ['province_id' => 14, 'name' => 'Kabupaten Barito Utara'],
            ['province_id' => 14, 'name' => 'Kabupaten Gunung Mas'],
            ['province_id' => 14, 'name' => 'Kabupaten Kapuas'],
            ['province_id' => 14, 'name' => 'Kabupaten Katingan'],
            ['province_id' => 14, 'name' => 'Kabupaten Kotawaringin Barat'],
            ['province_id' => 14, 'name' => 'Kabupaten Kotawaringin Timur'],
            ['province_id' => 14, 'name' => 'Kabupaten Lamandau'],
            ['province_id' => 14, 'name' => 'Kabupaten Murung Raya'],
            ['province_id' => 14, 'name' => 'Kabupaten Pulang Pisau'],
            ['province_id' => 14, 'name' => 'Kabupaten Seruyan'],
            ['province_id' => 14, 'name' => 'Kabupaten Sukamara'],
            ['province_id' => 14, 'name' => 'Kota Palangkaraya'],
            ['province_id' => 15, 'name' => 'Kabupaten Bulungan'],
            ['province_id' => 15, 'name' => 'Kabupaten Malinau'],
            ['province_id' => 15, 'name' => 'Kabupaten Nunukan'],
            ['province_id' => 15, 'name' => 'Kabupaten Tana Tidung'],
            ['province_id' => 15, 'name' => 'Kota Tarakan'],
            ['province_id' => 16, 'name' => 'Kabupaten Lebak'],
            ['province_id' => 16, 'name' => 'Kabupaten Pandeglang'],
            ['province_id' => 16, 'name' => 'Kabupaten Serang'],
            ['province_id' => 16, 'name' => 'Kabupaten Tangerang'],
            ['province_id' => 16, 'name' => 'Kota Cilegon'],
            ['province_id' => 16, 'name' => 'Kota Serang'],
            ['province_id' => 16, 'name' => 'Kota Tangerang'],
            ['province_id' => 16, 'name' => 'Kota Tangerang Selatan'],
            ['province_id' => 17, 'name' => 'Kabupaten Administrasi Kepulauan Seribu'],
            ['province_id' => 17, 'name' => 'Kota Administrasi Jakarta Barat'],
            ['province_id' => 17, 'name' => 'Kota Administrasi Jakarta Pusat'],
            ['province_id' => 17, 'name' => 'Kota Administrasi Jakarta Selatan'],
            ['province_id' => 17, 'name' => 'Kota Administrasi Jakarta Timur'],
            ['province_id' => 17, 'name' => 'Kota Administrasi Jakarta Utara'],
        ]);
    }
}
