<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('companies')->insert([
            ['name' => 'PT Acset Indonusa Tbk', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'PT Advics Manufacturing Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT. Agro Menara Rachmat', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Agro Nusa Abadi (ANA)', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT. Astragraphia Tbk', 'parent_company_id' =>  1, 'business_line_id' => 2],
            ['name' => 'PT Akashi Wahana Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Akebono Brake Astra Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Tunggal Perkasa Plantation (TPP)', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Astra Agro Lestari 1', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Astra Sedaya Finance', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT. Astra Daihatsu Motor - Karawang Assy Plant', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT. Astra Daihatsu Motor - Engine Plant', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT. Astra Daihatsu Motor - Casting Plant', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT. Astra Daihatsu Motor - Head Office', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT. Astra Daihatsu Motor - Parts Center', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT. Astra Daihatsu Motor - Sunter Assy Plants', 'parent_company_id' =>  6, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant 2 Pegangsaan', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant 3 Cikarang', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant 3A Cikarang', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant 4 Karawang', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant 5 Karawang', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant DMD', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant PQE', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant TSD', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Plant PC', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra Honda Motor - Head Office (Plant 1)', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk -  Honda Sales Operation (HSO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk -   Astraworld (AWSO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk - Head Office', 'parent_company_id' =>  10, 'business_line_id' => 8],
            ['name' => 'PT Astra International Tbk - Toyota Sales Operations (TSO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk -  Daihatsu Sales Operations (DSO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk - BMW Sales Operations (BSO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk - UD Trucks Sales Operations (UD SO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra International Tbk - Isuzu Sales Operations (ISO)', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Astra Juoku Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Komponen Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Nippon Gasket Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Otoparts Tbk - Head Office', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Otoparts - Divisi Nusa Metal', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Tol Nusantara', 'parent_company_id' =>  10, 'business_line_id' => 6],
            ['name' => 'PT Autoplastik Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT. Bhadra Cemerlang', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Bhadra Sukses', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Borneo Indah Marjaya', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Cakung Permata Nusa', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Century Batteries Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Chuhatsu Indonesia', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'PT Cipta Agro Nusantara', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Denso Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT DIC Astra Chemicals', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Ekadura Indonesia', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Evoluzione Tyres', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Federal Izumi Manufacturing', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Federal Nittan Industries', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Gaya Motor', 'parent_company_id' =>  10, 'business_line_id' => 3],
            ['name' => 'PT Gemala Kempa Daya', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT GS Battery', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Gunung Sejahtera Dua Indah', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Gunung Sejahtera Ibu Pertiwi', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Gunung Sejahtera Puti Pesona', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Gunung Sejahtera Yoli Makmur', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Indonesia Nippon Seiki', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Inti Ganda Perdana', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Inti Pantja Press Industries', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Isuzu Astra Motor Indonesia', 'parent_company_id' =>  15, 'business_line_id' => 3],
            ['name' => 'PT Kalimantan Prima Persada', 'parent_company_id' =>  8, 'business_line_id' => 4],
            ['name' => 'PT Karya Tanah Subur', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Karyanusa Eka Daya', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Kayaba Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Kimia Tirta Utama', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Komatsu Marketing and Support Indonesia (KMSI)', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'PT Komatsu Indonesia', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'PT Komatsu Reman Asia', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'Koperasi Astra International', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'PT Lestari Tani Teladan', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Letawa', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Lintas Marga Sedaya', 'parent_company_id' =>  9, 'business_line_id' => 6],
            ['name' => 'PT Mamuang', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Marga Harjaya Infrastruktur', 'parent_company_id' =>  9, 'business_line_id' => 6],
            ['name' => 'PT Marga Mandalasakti', 'parent_company_id' =>  7, 'business_line_id' => 6],
            ['name' => 'PT Nirmala Agro Lestari', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Nusa Keihin Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Palma Plantasindo', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Pamapersada Nusantara', 'parent_company_id' =>  8, 'business_line_id' => 4],
            ['name' => 'PT Pasangkayu', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Perkebunan Lembah Bhakti', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Perkebunan Lembah Bhakti 2', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Persada Bina Nusantara Abadi', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Persada Dinamika Lestari', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'Astratech', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'PT. Samadista karya', 'parent_company_id' =>  17, 'business_line_id' => 7],
            ['name' => 'PT Tokai Toyota Auto Body Extrusion', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'PT Serasi Autoraya', 'parent_company_id' =>  14, 'business_line_id' => 6],
            ['name' => 'PT Resin Plating Technology', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'PT Rimbunan Alam Sentosa', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sari Aditya Loka 1', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sari Aditya Loka 2', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sari Lembah Subur', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sawit Asahan Indah', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Showa Indonesia Manufacturing', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT SKF Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Subur Abadi Plantations', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Subur Agro Makmur', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sugity Creatives', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'PT Sukses Tani Nusasubur', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Sumber Kharisma Persada', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Surya Indah Nusantara Pagi', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Suryaraya Lestari 1', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Suryaraya Lestari 2', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Suryaraya Rubberindo Industries', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Tanjung Sarana Lestari', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT TD Automotive Compressor Indonesia', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'PT Tjahja Sakti Motor', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT Topy Palingda', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT Toyota Astra Motor', 'parent_company_id' =>  13, 'business_line_id' => 3],
            ['name' => 'PT Toyota Motor Manufacturing Indonesia', 'parent_company_id' =>  12, 'business_line_id' => 3],
            ['name' => 'TRAC Astra Rent Car', 'parent_company_id' =>  14, 'business_line_id' => 6],
            ['name' => 'PT Traktor Nusantara', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'PT Tribuana Mas', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT Tunggal Perkasa Plantations', 'parent_company_id' =>  3, 'business_line_id' => 5],
            ['name' => 'PT United Tractors', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'Yayasan Amaliah Astra', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'PT Yutaka Manufacturing Indonesia', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT. Hitachi Astemo', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT AT Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Aisin Indonesia', 'parent_company_id' =>  4, 'business_line_id' => 3],
            ['name' => 'PT Astra Digital Internasional', 'parent_company_id' =>  10, 'business_line_id' => 2],
            ['name' => 'PT Fuji Technica Indonesia', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT Pulogadung Pawitra Laksana', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT Federal International Finance', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Asuransi Jiwa Astra', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Astra Mitra Ventura', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Astra Multi Finance', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Asuransi Astra Buana', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Cipta Sedaya Digital Indonesia', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Sedaya Multi Investama', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Toyota Astra Financial Services', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Menara Astra', 'parent_company_id' =>  17, 'business_line_id' => 7],
            ['name' => 'PT Brahmayasa Bahtera', 'parent_company_id' =>  17, 'business_line_id' => 7],
            ['name' => 'PT Samadista Karya', 'parent_company_id' =>  17, 'business_line_id' => 7],
            ['name' => 'PT Astra Digital Mobil (OLXmobbi)', 'parent_company_id' =>  14, 'business_line_id' => 6],
            ['name' => 'PT Surya Arta Nusantara Finance (SANF)', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Komatsu Astra Finance', 'parent_company_id' =>  5, 'business_line_id' => 1],
            ['name' => 'PT Serasi Mitra Mobil', 'parent_company_id' =>  14, 'business_line_id' => 6],
            ['name' => 'PT Pakoakuina', 'parent_company_id' =>  18, 'business_line_id' => 3],
            ['name' => 'PT Harmoni Mitra Utama', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'PT United Tractors Pandu Engeneering', 'parent_company_id' =>  2, 'business_line_id' => 4],
            ['name' => 'Yayasan Insan Mulia Pama', 'parent_company_id' =>  8, 'business_line_id' => 9],
            ['name' => 'PT Sigap Prima Astrea', 'parent_company_id' =>  19, 'business_line_id' => 9],
            ['name' => 'Yayasan Dharma Bhakti Astra (YDBA)', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'Yayasan Pendidikan Astra-Michael D. Ruslim (YPA-MDR)', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'Yayasan Astra Honda Motor (YAHM)', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'Yayasan Toyota dan Astra (YTA)', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'Yayasan Karya Bakti United Tractors (YKBUT)', 'parent_company_id' =>  10, 'business_line_id' => 9],
            ['name' => 'Yayasan Astra Agro Lestari (YAAL)', 'parent_company_id' =>  10, 'business_line_id' => 9],        
        ]);
    }
}
